name: GCP RDP
on: [push, workflow_dispatch]

jobs:
  build:
  
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Baixando Ngrok
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/OneCloudService/GoogleCloudRDP/main/ngrok.zip -OutFile ngrok.zip
        https://raw.githubusercontent.com/OneCloudService/GoogleCloudRDP/main/rdp.bat -OutFile rdp.bat
    - name: Extraindo Ngrok
      run: Expand-Archive ngrok.zip
    - name: Auth Token
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Abrir TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
   
     - name: Criar Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region=sa 3389"'
      -name: Conectando RDP GCP
      run: cmd /c rdp.bat
      - name: 6 Horas Tempo
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/OneCloudService/GoogleCloudRDP/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
