name: GoogleCloud

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download do ngrok
      run: |
       Invoke-WebRequest https://raw.githubusercontent.com/OneCloudService/GoogleCloudRDP/main/ngrok.zip -OutFile ngrok.zip
       Invoke-WebRequest https://raw.githubusercontent.com/OneCloudService/GoogleCloudRDP/main/rdp.bat -OutFile rdp.bat
    - name: Extraindo Zip
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Configurando RDP
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp --region=sa 3389
    - name: 6 Horas Tempo
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/OneCloudService/GoogleCloudRDP/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
    
